services:
  iot-app:
    container_name: iot-app
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  iot-reciever:
    container_name: iot-reciever
    build:
      context: .
      dockerfile: build/reciver.Dockerfile
    ports:
      - "8001:8001"

  iot-mqtt:
    image: eclipse-mosquitto
    container_name: iot-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
